((nil . ((indent-tabs-mode . nil)
         (fill-column . 90)
         (compile-command . "./tools/dune_build.sh")
         (projectile-project-configure-cmd . "./bootstrap.sh")
         (projectile-project-compilation-cmd . "./tools/dune_build.sh")
         (projectile-project-test-cmd . "./tools/dune_test.sh")))
 (caml-mode . ((tab-width . 2)))
 (ocaml-ts-mode . ((tab-width . 2)))
 (tuareg-mode . ((tab-width . 2)
                 (tuareg-indent-align-with-first-arg . t)
                 (tuareg-match-patterns-aligned . t))))
