open! Core
open! Axis_width_adapter_8_to_64_testbench

let%test_unit "payload lengths one through seventeen pack into contiguous low lanes" =
  List.iter (List.range 1 18) ~f:(fun length ->
    let frame = List.init length ~f:(fun index -> ((index * 29) + 3) land 0xFF) in
    let observation = Testbench.run [ frame ] in
    [%test_result: Wide_beat.t list]
      ~message:(sprintf "payload length %d" length)
      observation.transfers
      ~expect:(expected [ frame ]))
;;

let%test_unit "frame boundaries never share a wide word" =
  let frames = [ [ 0xA1; 0xA2; 0xA3 ]; List.range 0x10 0x19 ] in
  let observation = Testbench.run frames in
  [%test_result: Wide_beat.t list] observation.transfers ~expect:(expected frames)
;;

let%test_unit "backpressure holds a completed word and stops the byte input" =
  let frame = List.range 1 13 in
  let ready cycle = cycle < 8 || cycle >= 13 in
  let observation = Testbench.run ~ready [ frame ] in
  [%test_result: Wide_beat.t list] observation.transfers ~expect:(expected [ frame ]);
  [%test_result: Wide_beat.t list]
    observation.stalled_outputs
    ~expect:(List.init 5 ~f:(fun _ -> List.hd_exn (expected [ frame ])));
  let stalled_cycles =
    List.filter observation.trace ~f:(fun cycle ->
      Option.is_some cycle.output && not cycle.output_ready)
  in
  List.iter stalled_cycles ~f:(fun cycle ->
    [%test_result: bool]
      ~message:"the narrow source is backpressured while the output register is full"
      cycle.source_ready
      ~expect:false)
;;

let%test_unit "generated byte streams round-trip through the widening contract" =
  let generator =
    let open Quickcheck.Generator.Let_syntax in
    let%bind frame_count = Int.gen_incl 1 4 in
    List.gen_with_length
      frame_count
      (let%bind length = Int.gen_incl 1 40 in
       List.gen_with_length length (Int.gen_incl 0 255))
  in
  Quickcheck.test
    ~seed:(`Deterministic "axis-width-adapter-8-to-64")
    ~trials:80
    generator
    ~f:(fun frames ->
      let observation = Testbench.run frames in
      [%test_result: Wide_beat.t list] observation.transfers ~expect:(expected frames))
;;
